{% set name = "sra-downloader" %}
{% set version = "1.0.4" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ae32385888f590ec46cbb2d3dec9e74aa0b3f611d3e1b6b7850ac51e623c392e

build:
  number: 0
  entry_points:
    - sra-downloader=sra_downloader.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sra-tools >=2.9.6
    - pigz >=2.6
test:
  imports:
    - sra_downloader
  commands:
    - sra-downloader --help

about:
  home: "https://github.com/bioinf-mcb/sra-downloader"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A script for batch-downloading and automatic compression of data from NCBI Sequence Read Archive. Built on SRA-Toolkit."
  doc_url: 
  dev_url: 
  description: {{ data.get('long_description') }}

extra:
  recipe-maintainers:
    - wwydmanski
